# SLR (FAKE DATASET)

In [ ]:
import numpy as np

np.random.seed(0)
X_simple = np.linspace(0, 10, 100).reshape(-1, 1)
y_simple = 2 * X_simple + 5 + np.random.randn(100, 1) * 2

X_simple_b = np.c_[np.ones((100, 1)), X_simple]

theta_simple = np.linalg.inv(X_simple_b.T.dot(X_simple_b)).dot(X_simple_b.T).dot(y_simple)

print("Simple Linear Regression Coefficients (theta):")
print(theta_simple)

Simple Linear Regression Coefficients (theta):
[[5.4169429 ]
 [1.94053463]]


# MLR (FAKE DATASET)

In [ ]:
import numpy as np

np.random.seed(0)
X_multiple = np.random.rand(100, 2) * 10
y_multiple = 3 * X_multiple[:, 0].reshape(-1, 1) + 4 * X_multiple[:, 1].reshape(-1, 1) + 10 + np.random.randn(100, 1) * 5

X_multiple_b = np.c_[np.ones((100, 1)), X_multiple]

theta_multiple = np.linalg.inv(X_multiple_b.T.dot(X_multiple_b)).dot(X_multiple_b.T).dot(y_multiple)

print("\nMultiple Linear Regression Coefficients (theta):")
print(theta_multiple)


Multiple Linear Regression Coefficients (theta):
[[10.57251628]
 [ 2.78685022]
 [ 4.01478753]]


# SLR (KAGGLE SAMPLE DATASET)

In [ ]:
import numpy as np
import pandas as pd

X_simple_df = pd.read_csv('/content/sample_data/Salary_dataset.csv')

X_simple = X_simple_df[['YearsExperience']].values
y_simple = X_simple_df['Salary'].values.reshape(-1, 1)

X_simple_b = np.c_[np.ones((X_simple.shape[0], 1)), X_simple]

theta_simple = np.linalg.inv(X_simple_b.T.dot(X_simple_b)).dot(X_simple_b.T).dot(y_simple)

print("Simple Linear Regression Coefficients (theta):")
print(theta_simple)

Simple Linear Regression Coefficients (theta):
[[24848.20396652]
 [ 9449.96232146]]


# MLR (KAGGLE SAMPLE DATASET)

In [ ]:
import numpy as np
import pandas as pd

X_multiple_df = pd.read_csv('/content/sample_data/Student_Performance.csv')

X_multiple = X_multiple = X_multiple_df[['Hours Studied', 'Previous Scores', 'Sleep Hours', 'Sample Question Papers Practiced']].values
y_multiple = X_multiple_df['Performance Index'].values.reshape(-1, 1)

X_multiple_b = np.c_[np.ones((X_multiple.shape[0], 1)), X_multiple]

theta_multiple = np.linalg.inv(X_multiple_b.T.dot(X_multiple_b)).dot(X_multiple_b.T).dot(y_multiple)

print("\nMultiple Linear Regression Coefficients (theta):")
print(theta_multiple)


Multiple Linear Regression Coefficients (theta):
[[-33.76372609]
 [  2.85342921]
 [  1.01858354]
 [  0.47633298]
 [  0.1951983 ]]
