<a href="https://colab.research.google.com/github/davesohamm/Nirma-Practical/blob/branch-2/AML/Ex_1_AML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import NumPy library to efficiently work with data structures like Matrices, Vectors and Tensors.

In [ ]:
import numpy as np

One Directional Array using Numpy

In [ ]:

row_array = np.array([1, 2, 3])
column_array = np.array([[1],
                         [2],
                         [3]])
print(f"Row Array: \n{row_array}")
print(f"Column Array: \n{column_array}")

Row Array: 
[1 2 3]
Column Array: 
[[1]
 [2]
 [3]]


Two Dimensional Array using Numpy

In [ ]:
twod_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(f"2D Array: \n{twod_array}")

2D Array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Two-Dimensional Matrix using np.asmatrix() method.

NOTE - np.mat() method is deprecated in new NumPy versions

In [ ]:
twod_matrix = np.asmatrix([[11, 12, 13],
                     [14, 15, 16],
                     [17, 18, 19]])
print(f"2D Matrix: \n{twod_matrix}")

2D Matrix: 
[[11 12 13]
 [14 15 16]
 [17 18 19]]


Sparse Matrix is a matrix with very few non-zero values. To efficiently represent the data, we use compressed sparsed row (CSR Matrix) method from the scipy library.

The Compressed Sparse Row (CSR) format is designed for fast row operations.
 It stores only the non-zero values and their corresponding column indices, along with pointers to the start of each row in the data array.

In [ ]:
from scipy import sparse

matrix_example = ([[1, 4, 0],
                         [0, 2, 0],
                         [5, 0, 3]])
matrix_sparse = sparse.csr_matrix(matrix_example)
print(f"Sparse Matrix (CSR): \n{matrix_sparse}")

Sparse Matrix (CSR): 
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (0, 1)	4
  (1, 1)	2
  (2, 0)	5
  (2, 2)	3


CSC Matrix method from scipy library.

the Compressed Sparse Column (CSC) format is optimized for fast column operations.
 It stores non-zero values and their corresponding row indices, with pointers to the start of each column in the data array.


In [ ]:
matrix_sparse = sparse.csc_matrix(matrix_example)
print(f"Sparse Matrix (CSC): \n{matrix_sparse}")

Sparse Matrix (CSC): 
<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 5 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (2, 0)	5
  (0, 1)	4
  (1, 1)	2
  (2, 2)	3


Let's Create a larger matrix to understand the sparse methods in better way.

In [ ]:
large_matrix = np.array([[1, 0, 0, 0, 4, 5, 0, 0],
                         [0, 0, 0, 0, 1, 1, 1, 0],
                         [1, 0, 0, 0, 0, 0, 0 ,0],
                         [2, 0, 0, 0, 0, 1, 0, 0]])
sparse_large_matrix = sparse.csr_matrix(large_matrix)
print(f"Sparse Matrix (CSR): \n{sparse_large_matrix}")


Sparse Matrix (CSR): 
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (4, 8)>
  Coords	Values
  (0, 0)	1
  (0, 4)	4
  (0, 5)	5
  (1, 4)	1
  (1, 5)	1
  (1, 6)	1
  (2, 0)	1
  (3, 0)	2
  (3, 5)	1


To select a specific element from a vector and matrix, we use the indexes.

In [ ]:
new_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_array[2]

np.int64(3)

In [ ]:
new_matrix = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15]])
new_matrix[2][3]

np.int64(14)

To select all the elements of the array, we use " : "

In [ ]:
new_array[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

To select all the elements to a certain index, we use " :n "

(NOTE - here all the elements starting from the index 0 to n (n included) will get selected)

In [ ]:
new_array[:4]

array([1, 2, 3, 4])

to select a last element from the array, we use [-1]

In [ ]:
new_array[-1]

np.int64(10)

In Matrix, we can select any rows and columns, by separating rows and columns by using " , " coma .

(NOTE - if we select matrix[:2, 1:3] it will select 0th and 1st row, and 1st and 2nd column.
where if we use [:, 1:3] it will select all the rows, and 1st and 2nd column.)

In [ ]:
new_matrix[:2, 1:3]

array([[2, 3],
       [7, 8]])

In [ ]:
new_matrix[:, 1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

We use " shape " method so know the dimensions of the matrix.
(NOTE- for the output (m, n), m is the number of rows and n is the number columns)

In [ ]:
new_matrix.shape

(3, 5)

" size " method shows the total number of elements in a matrix.

number of rows * number of columns

In [ ]:
new_matrix.size

15

If you want to know if you have 2 - dimensional matrix, or 3-dimensional matrix or multi-directional matrix, Use " ndim " method.

In [ ]:
new_matrix.ndim

2

We can use Lambda Functions to perform various operations on something. Lambda functions are particularly useful for creating short, simple functions on the fly.

(NOTE - Here we are using np.vectorize() function.
The np.vectorize function in NumPy is a convenience tool that takes a Python function and returns a vectorized version of it, allowing the function to be applied to entire arrays or sequences of objects.)

In [ ]:
# Create a function that adds 999 to something
add_999 = lambda i: i + 999

# Create vectorized function
vectorized_add_999 = np.vectorize(add_999)

# apply the function to all the elements of the matrix
vectorized_add_999(new_matrix)

array([[1000, 1001, 1002, 1003, 1004],
       [1005, 1006, 1007, 1008, 1009],
       [1010, 1011, 1012, 1013, 1014]])

(NOTE - vectorize method is same as a for loop. To increase the performance, we can use a method called broadcasting.)

In [ ]:
new_matrix + 2000

array([[2001, 2002, 2003, 2004, 2005],
       [2006, 2007, 2008, 2009, 2010],
       [2011, 2012, 2013, 2014, 2015]])

By using vectorize methods, we can specifically select a part of the matrix, where we want to use a function. And that will not be broadcasted on the entire matrix.

In [ ]:
add_500 = lambda i : i + 500
vectorized_add_500 = np.vectorize(add_500)
vectorized_add_500(new_matrix[:, 1:3])

array([[502, 503],
       [507, 508],
       [512, 513]])

To fin minimum and maximum values from the matrix, we use np.min and np.max inbuilt functions of NumPy

In [ ]:
np.max(new_matrix)

np.int64(15)

In [ ]:
np.min(new_matrix)

np.int64(1)

To find min or max for the specific row or column, we use the axis.

if axis = 1, we find the min/max row
if axis = 0, we find the min/max column

In [ ]:
np.max(new_matrix, axis = 1)

array([ 5, 10, 15])

In [ ]:
np.min(new_matrix, axis = 0)

array([1, 2, 3, 4, 5])

To find the mean of all the elements of a matrix, we use np.mean method

In [ ]:
np.mean(new_matrix)

np.float64(8.0)

To find the standard deviation, we use np.std method

In [ ]:
np.std(new_matrix)

np.float64(4.320493798938574)

To find the Variance, we use np.var method

In [ ]:
np.var(new_matrix)

np.float64(18.666666666666668)

To find the mean of all the rows we can use axis = 1, and for columns, we use axis = 0.

In [ ]:
np.mean(new_matrix, axis = 1)

array([ 3.,  8., 13.])

In [ ]:
np.mean(new_matrix, axis = 0)

array([ 6.,  7.,  8.,  9., 10.])

To reshape the matrix in terms of number of rows and columns without changing it's elements, we can use reshape(m , n) function.
where m = rows, n = columns

In [ ]:
new_matrix.reshape(5, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

To get only 1 column, and as many as rows as needed, we use reshape(-1, 1) funciton.

In [ ]:
new_matrix.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

To get only one row and as many as columns as needed, we use reshape(-1,1) function.

In [ ]:
new_matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

to check the size of atrix (m x n), we use size() function.

In [ ]:
new_matrix.size

15

Transpose means the rows and columns get swapped with each other. To find the matrix transpose, we use matrix_name.T method:

In [ ]:
new_matrix.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

Although, we cannot find Transpose of a vector, because it is just a collection of values. That's why the transpose of a vector is vector itself. Here is an example :

In [ ]:
np.array([10, 11, 12, 13, 14, 15]).T

array([10, 11, 12, 13, 14, 15])

To find a transpose of a linearly shaped matrix we entirely convert a row into a column or a column into a row.

NOTE- a vector is defined with only one pair of brackets []
where a matrix is defined with two pair of brackets [ [ ] ]

In [ ]:
np.array([[11, 12, 13, 14, 15]]).T

array([[11],
       [12],
       [13],
       [14],
       [15]])

No matter whatever dimension matrix you have, you can flatten it linearly using flatten() method.

In [ ]:
new_matrix.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

NOTE - flatten() method is used to transform a matrix into one-dimensional array.
But if we want to create a row matrix of an original matrix, we use the reshape(1, -1) method.

Look at the difference between one pair of brackets, and two pairs.

In [ ]:
new_matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

The rank of a matrix is the maximum number of linearly independent rows or columns in the matrix. It essentially indicates the dimension of the vector space spanned by the matrix's rows or columns. A matrix has rank 'r' if there exists at least one minor of order 'r' that is non-zero, and all minors of order (r+1) or higher are zero.

To find Rank of Matrix, we use np.linalg.matrix_rank(matrix_name) method. Here is an example :

In [ ]:
np.linalg.matrix_rank(new_matrix)

np.int64(2)

The determinant of a matrix is a scalar value that can be computed from the elements of a square matrix.

To find determinant of a matrix, we use np.linalg.det(matrix_name) method. here is an example :

In [ ]:
matrix_example = np.array([[90, 80, 70],
                         [60, 50, 40],
                         [30, 20, 10]])
np.linalg.det(matrix_example)

np.float64(4.263256414560599e-12)

To find the diagonal of the matrix, we use matrix_name.diagonal() method.

In [ ]:
matrix_example.diagonal()

array([90, 50, 10])

To find the anti-diagonal, firstly we have to flip the matrix using fliplr(). then use diagonal() method.

In [ ]:
np.fliplr(matrix_example).diagonal()

array([70, 50, 30])

We can also find diagonals off from the main diagonals using positive and negative offset values. Here is an example :

In [ ]:
matrix_example.diagonal(offset=1)

array([80, 40])

In [ ]:
matrix_example.diagonal(offset=-1)

array([60, 20])

Trace of matrix = Sum of all the diagonal elements of the matrix.
To find trace, we use trace() method directly.

In [ ]:
matrix_example.trace()

np.int64(150)

NOTE - We can also use the sum of matrix.diagonal() to find the trace of a matrix.

In [ ]:
sum(matrix_example.diagonal())

np.int64(150)

Eigenvalues are special scalar values associated with a square matrix that characterize its effect on eigenvectors. To find the eigenvalues of an $n \times n$ matrix $A$, we solve the characteristic equation: $det(A - \lambda I) = 0$, where $I$ is the identity matrix of the same size as $A$, and $det$ represents the determinant.

Eigenvectors are the non-zero vectors that, when acted upon by a matrix, only change in magnitude (stretched or compressed) but not in direction (or have their direction reversed). Once the eigenvalues are determined, the eigenvectors are found by solving the equation: $(A - \lambda I)v = 0$ for each eigenvalue $\lambda$. This equation represents a system of linear equations that, when solved, yields the eigenvectors corresponding to that eigenvalue.


To find eigenvalues and eigenvectors we use np.linalg.eig(matrix_name) method.

then to display the eigenvalues we write eigenvalues, and for eigenvectors we write eigenvectors, simply.

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix_example)


In [ ]:
eigenvalues

array([ 1.61168440e+02, -1.11684397e+01, -2.43383159e-15])

In [ ]:
eigenvectors

array([[-0.8186735 , -0.61232756,  0.40824829],
       [-0.52532209,  0.08675134, -0.81649658],
       [-0.23197069,  0.78583024,  0.40824829]])

The dot product, also known as the scalar product or inner product, is a mathematical operation that takes two vectors and returns a single scalar value. It's calculated by multiplying corresponding components of the vectors and summing the results.

to find a dot product of two vectors we use np.dot(vector_1, vector_2) method.

In [ ]:
vector_1 = np.array([101, 102, 103])
vector_2 = np.array([104, 105, 106])
np.dot(vector_1, vector_2)

np.int64(32132)

NOTE - In recent python versions, we can also use '@' as a dot multiplication operator.

In [ ]:
vector_1 @ vector_2

np.int64(32132)

To add two matrices, we use np.add(matrix_1, matrix_2) method.

In [ ]:
matrix_1 = np.array([[101, 201, 301],
                     [401, 501, 601],
                     [701, 801, 901]])
matrix_2 = np.array([[102, 202, 302],
                     [402, 502, 602],
                     [702, 802, 902]])

In [ ]:
np.add(matrix_1, matrix_2)

array([[ 203,  403,  603],
       [ 803, 1003, 1203],
       [1403, 1603, 1803]])

In the same way, to subtract matrix 2 from matrix 1, we use np.subtract(matrix_1, matrix_2) method.

In [ ]:
np.subtract(matrix_1, matrix_2)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

NOTE- We can also simple use + and - operator to show the addition and subtraction of two matrices.

In [ ]:
matrix_1 + matrix_2

array([[ 203,  403,  603],
       [ 803, 1003, 1203],
       [1403, 1603, 1803]])

In [ ]:
matrix_2 - matrix_1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

To find matrix dot multiplication we can use the same two mathods, np.dot(matrix_1, matrix_2) and '@' operator methods :

In [ ]:
np.dot(matrix_1, matrix_2)

array([[ 302406,  362706,  423006],
       [ 664206,  814506,  964806],
       [1026006, 1266306, 1506606]])

In [ ]:
matrix_1 @ matrix_2

array([[ 302406,  362706,  423006],
       [ 664206,  814506,  964806],
       [1026006, 1266306, 1506606]])

The inverse of a matrix, denoted as A⁻¹, is another matrix that, when multiplied by the original matrix A, results in the identity matrix.

To find the inverse of a matrix, we simply use np.linalg.inv(matrix_name) method :

In [ ]:
matrix_new = np.array([[1, 7],
                       [2, 4]])
np.linalg.inv(matrix_new)

array([[-0.4,  0.7],
       [ 0.2, -0.1]])

NOTE- if we multiply the inverse of a matrix with the matrix itself, it returns the identity matrix.

In [ ]:
matrix_new @ np.linalg.inv(matrix_new)

array([[ 1.00000000e+00, -8.32667268e-17],
       [ 0.00000000e+00,  1.00000000e+00]])

To generate pseudorandom values, we use np.random.random(n) method. where n = number of random values you want. if the range is not specified, it takes from 0 to 1 automatically.

NOTE- we use np.random.seed(0) method because random module typically uses the current system time as the default seed, resulting in different sequences of numbers each time the program is executed.

In [ ]:
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

To find random values for a custom range, we use

np.random.randint(lower_limit, higher_limit, number of values you want)

In [ ]:
np.random.randint(0, 100, 10)

array([21, 36, 87, 70, 88, 88, 12, 58, 65, 39])

To draw n numbers from a normal distribution with mean m and standard deviation sd, we use the method

np.random.normal(m, sd, n)

In [ ]:
np.random.normal(0.0, 2.0, 5)

array([ 5.09040156,  2.16162383,  0.96862431,  1.15828096, -0.36316515])

To draw n numbers from a logistic distribution with mean m and scale of s, we use the method

np.random.logistic(m, s, n)

In [ ]:
np.random.logistic(0.0, 2.0, 5)

array([ 2.53750564, -4.0177466 ,  1.15004274, -3.57542694,  5.67499937])

To draw n numbers greater than or equal to l and less than h we use the method

np.random.uniform(l, h, n)

In [ ]:
np.random.uniform(1.0, 5.0, 5)

array([3.08739329, 2.65864776, 2.05822245, 4.09693476, 2.82460133])