<a href="https://colab.research.google.com/github/davesohamm/Nirma-Practical/blob/main/AML/Ex_2_AML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

To print numpy version we use print(np.__version__) and to print the configuration of numpy we can use np.show_config() method

In [ ]:
print(np.__version__)

2.0.2


In [ ]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


to create a null vector of size n, we use np.zeros(n) method

In [ ]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


To find the memory size of any array, we use (z.size * z.itemsize) :

In [ ]:
y = np.zeros((10,10))
print("%d bytes" % (y.size * y.itemsize))

800 bytes


To get the documentation of any nupy function like add, subtract, etc.. from the command line itself, we use this command :

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
np.info(np.subtract)

subtract(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Subtract arguments, element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be subtracted from each other.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created v

to manipulate the value of an array :

In [ ]:
x = np.zeros(10)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


create a vector with values ranging m to n, we use np.arange(m, n+1) method :

In [ ]:
a = np.arange(10, 100)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


To reverse a vector we use [::-1] after the vector name :

In [ ]:
b = a[::-1]
print(b)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


To create an $n$ x $n$ matrix with values ranging from 0 to m, we use

np.range(m).reshape(n, n) method :

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

to find nonzero element indices from an array, we use np.nonzero([array]) method

In [ ]:
nz = np.nonzero([1, 2, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 0, 3])
print(nz)

(array([ 0,  1,  4,  9, 13]),)


To create $n$x$n$ identity matrix we use np.eye(n) method :

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

To create $n$ x $n$ x $n$ array with random values, we use np.random.random((n,n,n))

In [ ]:
np.random.random((3,3,3))

array([[[0.6965113 , 0.72888863, 0.07900998],
        [0.1920371 , 0.72219168, 0.51300341],
        [0.78168027, 0.33112485, 0.29181049]],

       [[0.04448342, 0.06816674, 0.82482709],
        [0.62449402, 0.10202458, 0.93247647],
        [0.45231274, 0.06239044, 0.67781122]],

       [[0.29631658, 0.52907726, 0.28292771],
        [0.99812368, 0.5429802 , 0.85017642],
        [0.51725191, 0.11114353, 0.23249767]]])

To find the minimum and maximum values of a matrix, we use min() and max() methods :

In [ ]:
array_example = np.random.random((10, 10))
array_min, array_max = array_example.min(), array_example.max()
print(f"The minimum value of array is {array_min}", f"\n The maximum value of array is {array_max}")

The minimum value of array is 0.00260852834573011 
 The maximum value of array is 0.9900539582090284


To find the mean value of an array, we use mean() method.


In [ ]:
mean_array = np.random.random(30)
print(mean_array.mean())

0.5031276271284387


To create a 2D array with 1 on the border and 0 inside, we can use this method :

In [ ]:
zero_one_array = np.ones((10, 10))
zero_one_array[1:-1, 1:-1] = 0
print(zero_one_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


If you want to add a border filled with 0's around an existing array, you can use this method :

In [ ]:
zero_border_array = np.ones((5, 5))
zero_border_array = np.pad(zero_border_array, pad_width=1, mode='constant', constant_values=0)
print(zero_border_array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
print(0 * np.nan)

nan


In [ ]:
print(np.nan == np.nan)

False


In [ ]:
print(np.inf > np.nan)

False


In [ ]:
print(np.inf)

inf


In [ ]:
print(np.nan - np.nan)

nan


In [ ]:
print(np.nan in set([np.nan]))

True


In [ ]:
print(0.3 == 3 * 0.1)

False


In [ ]:
print(np.nan)

nan


In [ ]:
print(0.3)

0.3


In [ ]:
print(3*0.1)

0.30000000000000004


In [ ]:
print(np.inf > 100000000)

True


create a 5x5 matrix with values 1,2,3,4 just below the diagonal :

In [ ]:
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


create a 8x8 matrix and fill it with a checkerboard pattern.

In [ ]:
z = np.zeros((8,8), dtype = int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Consider a (6,7,8) shape array, what is the index(x,y,z) of the 100th element ?

In [ ]:
print(np.unravel_index(99, (6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


create a checkerboard 8 x 8 matrix using the tile function :

In [ ]:
z = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


normalize a 5 x 5 random matrix :

In [ ]:
z = np.random.random((5,5))
print(z)
print(np.mean(z))
print(np.std(z))
z = (z - np.mean(z)) / (np.std(z))
print(z)

[[0.79066879 0.0617684  0.38791749 0.1565499  0.57562212]
 [0.2212408  0.10334087 0.03150479 0.31099364 0.26315207]
 [0.81585408 0.15510598 0.6583875  0.10433744 0.70590771]
 [0.49533347 0.08040997 0.91781716 0.91248506 0.14206389]
 [0.62550442 0.20012703 0.9318953  0.8889169  0.65623906]]
0.4477257534948555
0.3130717840207721
[[ 1.09541344 -1.23280786 -0.19103689 -0.93006099  0.4085209 ]
 [-0.72342819 -1.10001892 -1.32947453 -0.43674364 -0.58955708]
 [ 1.17585917 -0.93467309  0.67288639 -1.0968357   0.82467334]
 [ 0.15206644 -1.17326377  1.50154511  1.48451356 -0.97633155]
 [ 0.56785272 -0.79086884  1.54651288  1.40923317  0.66602394]]


given a 1d array, negate all elements whicha re between 3 and 8, in place.

In [ ]:
z = np.arange(11)
print(z)
z[(3<z) & (z<=8)] *= -1
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


consider an integer vector z, which of these expressins are legal :

To find common values between two arrays :

This code calculates the value of `z` raised to the power of `z`.

In [ ]:
z=4
z**z

256

This code prints the value of `z` raised to the power of `z`.

In [ ]:
print(z**z)

256


This code demonstrates bitwise left and right shifts. `2 << z` shifts 2 left by `z` bits (2 * 2^z), and then `>> 2` shifts the result right by 2 bits (divides by 2^2).

In [ ]:
print(2<<z>>2)

8


This code checks if `z` is less than the negation of `z`. Since `z` is 4, this evaluates to `4 < -4`, which is False.

In [ ]:
print(z <- z)

False


This code multiplies `z` by the imaginary unit `1j`, resulting in a complex number.

In [ ]:
print(1j*z)

4j


This code divides `z` by 1 twice, which is equivalent to `z / 1`, resulting in a float.

In [ ]:
print(z/1/1)

4.0


This code checks if `z` is less than `z` AND if `z` is greater than `z`. Both conditions are False, so the result is False.

In [ ]:
print(z<z>z)

False


In [ ]:
z1 = np.random.randint(0,10,10)
print(z1)
z2 = np.random.randint(0,10,10)
print(z2)
print(np.intersect1d(z1, z2))

[7 7 2 7 5 2 8 2 5 7]
[1 2 0 1 7 7 1 4 8 1]
[2 7 8]


How to get the dates of yesterday, today and tomorrow :

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2025-08-17 2025-08-18 2025-08-19


how to get all the dates corresponding to the month of July 2016 :

In [ ]:
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


extract the integer part of a random array using 5 different methods :

In [ ]:
z = np.random.uniform(0,10,10)
print(z)
print(z - z%1)
print(np.floor(z))
print(np.ceil(z) - 1)
print(z.astype(int))

[9.23036799 8.98579661 7.13431097 1.19754567 3.3365376  2.52639926
 6.71154079 6.47356692 0.08042839 7.1912224 ]
[9. 8. 7. 1. 3. 2. 6. 6. 0. 7.]
[9. 8. 7. 1. 3. 2. 6. 6. 0. 7.]
[9. 8. 7. 1. 3. 2. 6. 6. 0. 7.]
[9 8 7 1 3 2 6 6 0 7]


create a 5x5 matrix with row values ranging from 0 to 4:

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


create a random vector of size 10 and sort it :

In [ ]:
z = np.random.random(10)
z.sort()
print(z)

[0.12495762 0.16899343 0.21808144 0.39442961 0.58566945 0.76008664
 0.77434841 0.77965993 0.86461545 0.92032071]


consider two random array  A and B, check if they are equal using np.allcose(A,B) methods. If they are equal, it will return True otherwise False :

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A, B)
print(equal)

False


to make an array immutable, we have to set the flag writable to False. After that, the array becomes red-only.

In [ ]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

You can see, how it is giving a ValueError : assignment destination is read-only.

print the minimum and maximum representable value for each numpy scalar type :

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


It  iterates through the integer data types np.int8, np.int32, and np.int64. For each data type, it prints the minimum and maximum representable values using np.iinfo(dtype).min and np.iinfo(dtype).max.

In [ ]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


It  iterates through the floating-point data types np.float32 and np.float64. For each data type, it prints the minimum and maximum representable values using np.finfo(dtype).min and np.finfo(dtype).max. It also prints the machine epsilon (np.finfo(dtype).eps), which is the difference between 1.0 and the next smallest representable floating-point number greater than 1.0.

to find the closest value (to a given scalar) in a vector we use this method :

In [ ]:
z = np.arange(100)
v = np.random.uniform(0, 100)
print(v)
index = (np.abs(z-v)).argmin()
print(z[index])

67.06900535025626
67


np.abs(z - v): This calculates the absolute difference between each element in the array z and the scalar value v. This gives you an array of the distances between each element and v.

.argmin(): This method is called on the array of absolute differences. It returns the index of the minimum value in that array. Since we calculated the absolute differences, the minimum value corresponds to the element in the original array z that was closest to v.

consider a random vector with shape (100,2) represnting coordinates, find point by point distances.

In [ ]:
z = np.random.random((10,2))
x, y = np.atleast_2d(z[:,0], z[:,1])
print(x)
print(y)
d = np.sqrt((x-x.T)**2 + (y-y.T)**2)

[[0.95021611 0.3726957  0.22465285 0.84644234 0.96237409 0.1988271
  0.18941557 0.53384501 0.04152352 0.80551502]]
[[0.72622332 0.36554918 0.33106159 0.12203579 0.08442818 0.43782835
  0.01425823 0.32792773 0.98954147 0.25516632]]


It calculates point-by-point distances. It uses np.atleast_2d to ensure the coordinate arrays are at least 2D, and then applies broadcasting to calculate the squared differences and sum them before taking the square root for the distance.

It is much faster using Scipy.

In [ ]:
import scipy
import scipy.spatial

z = np.random.random((10,2))
d = scipy.spatial.distance.cdist(z,z)
print(d)

[[0.         0.57562218 0.356294   0.46618082 0.05319467 0.37176387
  0.12679898 0.29206229 0.36258188 0.49478284]
 [0.57562218 0.         0.30885232 0.71721561 0.6269264  0.22681698
  0.55177358 0.32978384 0.65818282 0.45725031]
 [0.356294   0.30885232 0.         0.69284273 0.39640829 0.09901348
  0.28150357 0.06822395 0.34938779 0.54443311]
 [0.46618082 0.71721561 0.69284273 0.         0.48666768 0.63862133
  0.58646068 0.62922439 0.82690852 0.30185786]
 [0.05319467 0.6269264  0.39640829 0.48666768 0.         0.41934192
  0.13845364 0.33471796 0.3554089  0.53976425]
 [0.37176387 0.22681698 0.09901348 0.63862133 0.41934192 0.
  0.3285164  0.10298014 0.43991893 0.45993585]
 [0.12679898 0.55177358 0.28150357 0.58646068 0.13845364 0.3285164
  0.         0.23014682 0.24076654 0.57339918]
 [0.29206229 0.32978384 0.06822395 0.62922439 0.33471796 0.10298014
  0.23014682 0.         0.34366569 0.49838643]
 [0.36258188 0.65818282 0.34938779 0.82690852 0.3554089  0.43991893
  0.24076654 0.343665

Using scipy.spatial.distance.cdist is generally faster for calculating pairwise distances because it's implemented in optimized C code, leveraging underlying libraries that are highly efficient for numerical operations.


Other SciPy spatial distance functions that can perform better than manual NumPy calculations for specific tasks include:

scipy.spatial.distance.pdist: Calculates pairwise distances between observations in a matrix (useful when you need all pairwise distances).

scipy.spatial.distance.euclidean: Calculates the Euclidean distance between two points.

scipy.spatial.distance.cosine: Calculates the cosine distance between two vectors.

how to convert a float (32 bits) array into an integer (32 bits) in place :

In [ ]:
z = np.arange(10, dtype=np.float32)
print(z)
z = z.astype(np.int32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


This is how we read files using stringIO:

In [ ]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z = np.genfromtxt(s, delimiter=",", dtype=int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


It reads data from a string that's formatted like a CSV. It uses np.genfromtxt to parse the string, treating commas as delimiters. The dtype=int argument specifies that the data should be interpreted as integers, and np.genfromtxt automatically handles the missing values by replacing them with a default value (in this case, -1 for integers).

Subtract the mean of each row of a matrix :

In [ ]:
x = np.random.rand(5, 10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[-0.38448349  0.30133158 -0.30835093 -0.08655142  0.20944278  0.27491942
  -0.170339    0.33114523  0.31685486 -0.48396903]
 [-0.02143797 -0.18126024  0.36311639 -0.50030657  0.19464785  0.199037
   0.11593281  0.43350443 -0.32617029 -0.2770634 ]
 [-0.32532134  0.53970708  0.26243672 -0.381206    0.08354037 -0.39181158
   0.54082999  0.20609599 -0.38447816 -0.14979308]
 [ 0.10170668 -0.33057087  0.32932728 -0.09461224  0.2667343   0.11971232
   0.26633154 -0.24973224  0.15448544 -0.56338219]
 [ 0.21003632  0.42584762  0.05956172 -0.09812981 -0.11002076 -0.12714081
  -0.26541058 -0.36889085 -0.15357313  0.42772027]]


how to sort an array by the nth column :

In [ ]:
z = np.random.randint(0, 10, (3,3))
print(z)
print(z[z[:,1].argsort()])

[[1 9 0]
 [9 7 9]
 [5 8 2]]
[[9 7 9]
 [5 8 2]
 [1 9 0]]


to tell if a given 2d array has null columns or not, we can use this method :

In [ ]:
z = np.random.randint(0,3,(3,10))
print(z)
print((~z.any(axis=0)).any())

[[2 2 0 2 1 2 0 0 1 2]
 [1 1 2 0 0 0 1 0 1 0]
 [0 1 0 0 1 0 2 1 2 0]]
False


z.any(axis=0): This checks if any element is non-zero along each column (axis 0). It returns a boolean array where True means the column has at least one non-zero element, and False means the column contains only zeros.


~: This is the bitwise NOT operator, which inverts the boolean array. Now, True means the column contains only zeros, and False means it has at least one non-zero element.

find the nearest value from a given value in an array :

In [ ]:
z = np.random.uniform(0,1,10)
print(z)
y = 0.5
m = z.flat[np.abs(z-y).argmin()]
print(m)

[0.84361923 0.71520507 0.10661438 0.13995118 0.96774483 0.00386829
 0.27271326 0.9508317  0.8370423  0.75182458]
0.715205074627952


.argmin(): Finds the index of the smallest absolute difference.


z.flat[...]: Uses the index found in the previous step to access the element in the original array z that corresponds to the smallest difference (i.e., the closest value to y).

How to accumulate elements of a vector X in an array F based on an index list I :

In [ ]:
X = [7,8,9,10,11,12]
I = [13, 14, 15, 16, 17, 18]
F = np.bincount(I,X)
print(F)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  7.  8.  9. 10. 11.
 12.]


This code uses np.bincount(I, X) to sum the values in X at the indices specified by I. It essentially accumulates the elements of X into bins determined by the values in I.

how to get the diagonal of a dot product :

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))


In [ ]:
np.diag(np.dot(A,B))

array([0.71813038, 0.78658176, 0.54496114, 1.49550446, 1.58654202])

This is a slower version.

In [ ]:
np.sum(A * B.T, axis=1)

array([0.71813038, 0.78658176, 0.54496114, 1.49550446, 1.58654202])

This is a Fast version.

In [ ]:
np.einsum("ij,ji->i", A,B)

array([0.71813038, 0.78658176, 0.54496114, 1.49550446, 1.58654202])

This is a faster version.


*  (`np.diag(np.dot(A,B))`): This method first computes the complete matrix multiplication of A and B using `np.dot()`. After obtaining the full resulting matrix, it then extracts the diagonal elements using `np.diag()`. This is generally the slowest because computing the full dot product involves many unnecessary calculations for the off-diagonal elements when you only need the diagonal.

*   (`np.sum(A * B.T, axis=1)`): This approach leverages the fact that the diagonal elements of A dotted with B are the sum of the element-wise products of the rows of A and the corresponding columns of B (which are the rows of B transposed, `B.T`). It performs an element-wise multiplication (`A * B.T`) and then sums across the rows (`axis=1`). This avoids calculating the full dot product matrix and is more efficient than the first method.

*  (`np.einsum("ij,ji->i", A,B)`): This method uses `np.einsum`, which is designed for efficient summation of products over specified indices. The string `"ij,ji->i"` is an Einstein summation convention that precisely describes the desired operation: multiply elements `A[i,j]` and `B[j,i]` and sum over the `j` index for each `i`. This directly computes only the required diagonal elements, making it the most optimized and fastest method among the three for this specific task.

Consider the vector [1,2,3,4,5] how to build a new vectory with 3 consecutive zeros interleaved between each value :

In [ ]:
z = np.array([1,2,3,4,5])
nz = 3
z0 = np.zeros(len(z) + (len(z)-1)*(nz))
z0[::nz+1] = z
print(z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


*   `z = np.array([1,2,3,4,5])`: Creates a NumPy array `z`.
*   `nz = 3`: Sets the number of zeros to interleave.
*   `z0 = np.zeros(len(z) + (len(z)-1)*(nz))`: Creates a new zero-filled array `z0` of the correct size.
*   `z0[::nz+1] = z`: Places the elements of `z` into `z0` with `nz` zeros in between.
*   `print(z0)`: Prints the resulting array.


to swap two rows of an array, just interchange like this :

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A[[3,4]] = A[[4,3]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [15 16 17 18 19]]


how to compute averages using a sliding window over an array ?

In [ ]:
def moving_average(a, n=3):
  ret = np.cumsum(a, dtype=float)
  ret[n:] = ret[n:] - ret[:-n]
  return ret[n-1:] / n
z = np.arange(20)
print(moving_average(z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


This function efficiently calculates the moving average using cumulative sums. It computes the cumulative sum of the array, then subtracts the cumulative sum shifted by n to get the sum of each window, and finally divides by n to get the average.

consider 2 sets of points P0, P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i]) :

In [ ]:
def distance(P0, P1, p):
  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U), 1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10, 10, (10,2))
p = np.random.uniform(-10, 10, (1,2))
print(distance(P0, P1, p))

[ 4.65744949  0.70552213  9.91197616  1.99936415 10.55621751  5.4695493
  2.13834053  9.25870784  4.98500605  7.77297165]


1.  **`T = P1 - P0`**: Calculates the direction vectors for each line.
2.  `L = (T**2).sum(axis=1)`: Calculates the squared length of each direction vector.
3.  `U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L`: Calculates the projection of the vector from `P0` to `p` onto the direction vector `T`, normalized by the squared length `L`. This gives a scalar value `U` for each line.
4.  `U = U.reshape(len(U), 1)`: Reshapes `U` to be a column vector to allow for broadcasting in the next step.
5.  `D = P0 + U*T - p`: Calculates the vector `D` from point `p` to the closest point on each line.
6.  `return np.sqrt((D**2).sum(axis=1))`: Calculates the magnitude of vector `D` for each line (the distance) and returns the array of distances.
7.  `P0 = np.random.uniform(-10, 10, (10,2))`: Creates an array `P0` of 10 random 2D points.
8.  `P1 = np.random.uniform(-10, 10, (10,2))`: Creates an array `P1` of 10 random 2D points. `P0` and `P1` define 10 lines.
9.  `p = np.random.uniform(-10, 10, (1,2))`: Creates a single random 2D point `p`.
10. `print(distance(P0, P1, p))`: Calls the `distance` function with the generated points and prints the calculated distances from point `p` to each of the 10 lines.

Now we have changed p from a set of points P. So we have to calculate distance from each point j (P[j]) to each line i (P0[i],P1[i]) :

In [ ]:
print(np.array([distance(P0, P1, p_i) for p_i in p]))

[[ 4.65744949  0.70552213  9.91197616  1.99936415 10.55621751  5.4695493
   2.13834053  9.25870784  4.98500605  7.77297165]]


We use bincount() and argmax() function to find the most frequent value in an array :

In [ ]:
z = np.random.randint(1,10,50)
print(np.bincount(z).argmax())

6


extract all the contiguous 3x3 blocks from a random 10x10 matrix :

In [ ]:
from numpy.lib import stride_tricks

z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (z.shape[0]-3)
j = 1 + (z.shape[1]-3)
c = stride_tricks.as_strided(z, shape=(i,j,n,n), strides=z.strides + z.strides)
print(c)

[[[[2 4 4]
   [0 0 4]
   [1 1 3]]

  [[4 4 3]
   [0 4 2]
   [1 3 1]]

  [[4 3 2]
   [4 2 0]
   [3 1 0]]

  [[3 2 0]
   [2 0 1]
   [1 0 0]]

  [[2 0 0]
   [0 1 3]
   [0 0 3]]

  [[0 0 1]
   [1 3 3]
   [0 3 2]]

  [[0 1 4]
   [3 3 0]
   [3 2 2]]

  [[1 4 1]
   [3 0 3]
   [2 2 0]]]


 [[[0 0 4]
   [1 1 3]
   [4 4 1]]

  [[0 4 2]
   [1 3 1]
   [4 1 0]]

  [[4 2 0]
   [3 1 0]
   [1 0 4]]

  [[2 0 1]
   [1 0 0]
   [0 4 0]]

  [[0 1 3]
   [0 0 3]
   [4 0 4]]

  [[1 3 3]
   [0 3 2]
   [0 4 1]]

  [[3 3 0]
   [3 2 2]
   [4 1 4]]

  [[3 0 3]
   [2 2 0]
   [1 4 1]]]


 [[[1 1 3]
   [4 4 1]
   [3 1 0]]

  [[1 3 1]
   [4 1 0]
   [1 0 3]]

  [[3 1 0]
   [1 0 4]
   [0 3 3]]

  [[1 0 0]
   [0 4 0]
   [3 3 2]]

  [[0 0 3]
   [4 0 4]
   [3 2 3]]

  [[0 3 2]
   [0 4 1]
   [2 3 0]]

  [[3 2 2]
   [4 1 4]
   [3 0 2]]

  [[2 2 0]
   [1 4 1]
   [0 2 1]]]


 [[[4 4 1]
   [3 1 0]
   [0 3 4]]

  [[4 1 0]
   [1 0 3]
   [3 4 1]]

  [[1 0 4]
   [0 3 3]
   [4 1 1]]

  [[0 4 0]
   [3 3 2]
   [1 1 3]]

  [[4 0 4]
   

In a 16x16 array, to get the block-sum of all 4x4 blocks we use :

In [ ]:
z = np.ones((16,16))
k=4
S= np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0),
                   np.arange(0,z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


1.  **`z = np.ones((16,16))`**: Creates a 16x16 NumPy array `z` filled with ones.
2.  **`k = 4`**: Sets the size of the blocks to 4x4.
3.  **`np.arange(0, z.shape[0], k)`**: Creates an array of indices `[0, 4, 8, 12]` for the rows.
4.  **`np.add.reduceat(z, ..., axis=0)`**: Sums the elements of `z` along columns (axis 0) at the specified row indices. This effectively sums each 4x4 block vertically.
5.  **`np.arange(0, z.shape[1], k)`**: Creates an array of indices `[0, 4, 8, 12]` for the columns.
6.  **`np.add.reduceat(..., ..., axis=1)`**: Sums the result of the previous step along rows (axis 1) at the specified column indices. This completes the summation of each 4x4 block horizontally.
7.  **`S = ...`**: Assigns the final block-sum matrix to the variable `S`.
8.  **`print(S)`**: Prints the resulting 4x4 matrix `S` containing the sums of the blocks.

to get the n largest value of an array, we have two methods :

In [ ]:
z = np.arange(10000)
np.random.shuffle(z)
n = 5

print(z[np.argsort(z)[-n:]])

[9995 9996 9997 9998 9999]


In [ ]:
print(z[np.argpartition(-z,n)[:n]])

[9999 9998 9997 9996 9995]


np.argpartition is faster because it only partially sorts the array to find the indices of the n largest elements, whereas np.argsort fully sorts the entire array.

Compute bootstrapped 95% confidence intervals for the mean of a 1D array X :

In [ ]:
x = np.random.randn(100)
n = 1000
idx = np.random.randint(0,x.size, (n, x.size))
means = x[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22879742  0.19128686]


1.  **`x = np.random.randn(100)`**: Creates a 1D NumPy array `x` with 100 random values from a standard normal distribution.
2.  **`n = 1000`**: Sets the number of bootstrap samples to 1000.
3.  **`idx = np.random.randint(0,x.size, (n, x.size))`**: Creates an array of random indices with dimensions (1000, 100). This array will be used to resample `x` with replacement for each bootstrap sample.
4.  **`means = x[idx].mean(axis=1)`**: Uses the `idx` array to select elements from `x` (performing resampling) and then calculates the mean of each of the 1000 bootstrap samples along `axis=1`.
5.  **`confint = np.percentile(means, [2.5, 97.5])`**: Calculates the 2.5th and 97.5th percentiles of the bootstrap means. These percentiles represent the lower and upper bounds of the 95% confidence interval.
6.  **`print(confint)`**: Prints the calculated 95% confidence interval for the mean of `x`.